[package]
name = "basket-service"
version.workspace = true
edition.workspace = true
description = "Starts transactions and scans items into baskets"

[dependencies]
axum.workspace = true
checkout-data.workspace = true
serde.workspace = true
serde_json.workspace = true
service-kit.workspace = true
tokio.workspace = true
